version: 2

project_name: burrow

before:
  hooks:
    - go work sync

builds:
  - id: burrowd
    dir: burrowd
    binary: burrowd
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X burrowd/main.Version={{.Version}}

  - id: burrowctl
    dir: burrowctl
    binary: burrowctl
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X burrowctl/main.Version={{.Version}}

archives:
  - id: burrowd
    ids: [burrowd]
    name_template: "burrowd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    wrap_in_directory: false

  - id: burrowctl
    ids: [burrowctl]
    name_template: "burrowctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    wrap_in_directory: false

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: miniaxolotl
    name: burrow
  draft: false
  prerelease: auto

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
