name: 'ci'

on:
  push:
    branches:
      - development
      - production

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build burrowctl
        run: cd burrowctl && go build -o ../bin/burrowctl .

      - name: Build burrowd
        run: cd burrowd && go build -o ../bin/burrowd .

  deploy-dev:
    needs: build
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL_DEV }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-prod:
    needs: build
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
