name: ci

on:
  push:
    branches:
      - development
      - production

jobs:
  deploy-preview:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to preview
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL_PREVIEW }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: main

  deploy-production:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to production
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: main
